-- MySQL 8; timestamps stored in UTC. App reports in Asia/Jakarta.
CREATE TABLE IF NOT EXISTS users (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL,
 email VARCHAR(190) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL,
 session_version INT UNSIGNED NOT NULL DEFAULT 1,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS site_settings (
 id INT UNSIGNED PRIMARY KEY, lab_name VARCHAR(150) NOT NULL, tagline VARCHAR(200) NOT NULL,
 show_lab_name BOOLEAN NOT NULL DEFAULT TRUE,
 greeting VARCHAR(200) NOT NULL, logo_path VARCHAR(255), address VARCHAR(500) NOT NULL,
 opening_hours JSON NOT NULL, primary_color CHAR(7) NOT NULL DEFAULT '#004aad',
 accent_color CHAR(7) NOT NULL DEFAULT '#ffde59', default_maps_url VARCHAR(2048) NOT NULL,
 default_wa_number VARCHAR(20) NOT NULL, default_wa_message VARCHAR(1000) NOT NULL,
 default_contact_id BIGINT UNSIGNED NULL, marketing_noindex BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS branches (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(150) NOT NULL,
 address VARCHAR(500) NOT NULL, maps_url VARCHAR(2048) NOT NULL, is_active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS contacts (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, slug VARCHAR(80) NOT NULL UNIQUE,
 name VARCHAR(100) NOT NULL, job_title VARCHAR(100) NOT NULL, photo_path VARCHAR(255),
 wa_number VARCHAR(20) NOT NULL, wa_message VARCHAR(1000) NOT NULL, branch_id BIGINT UNSIGNED NULL,
 is_active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY (branch_id) REFERENCES branches(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
ALTER TABLE site_settings ADD CONSTRAINT fk_default_contact FOREIGN KEY (default_contact_id) REFERENCES contacts(id) ON DELETE SET NULL;
CREATE TABLE IF NOT EXISTS extra_buttons (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, title VARCHAR(100) NOT NULL, url VARCHAR(2048) NOT NULL,
 icon ENUM('phone','instagram','website','catalog') NOT NULL DEFAULT 'website',
 sort_order INT NOT NULL DEFAULT 0, is_active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS visits (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, contact_id BIGINT UNSIGNED NULL,
 visited_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, device_type ENUM('mobile','tablet','desktop') NOT NULL,
 referrer VARCHAR(2048) NOT NULL DEFAULT '', ip_hash CHAR(64) NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX (visited_at,contact_id), INDEX (contact_id,visited_at),
 FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS clicks (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, contact_id BIGINT UNSIGNED NULL,
 button_type ENUM('whatsapp','maps','phone','other') NOT NULL,
 clicked_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, device_type ENUM('mobile','tablet','desktop') NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX (clicked_at,contact_id), INDEX (contact_id,clicked_at),
 FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS sessions (
 session_id VARCHAR(128) COLLATE utf8mb4_bin NOT NULL PRIMARY KEY,
 expires INT UNSIGNED NOT NULL, data MEDIUMTEXT COLLATE utf8mb4_bin,
 INDEX (expires)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS short_links (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 title VARCHAR(150) NOT NULL, slug VARCHAR(80) CHARACTER SET ascii COLLATE ascii_bin NOT NULL UNIQUE,
 target_url VARCHAR(2048) NOT NULL, is_active BOOLEAN NOT NULL DEFAULT TRUE,
 click_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS bio_settings (
 id INT UNSIGNED PRIMARY KEY, title VARCHAR(150) NOT NULL,
 description VARCHAR(500) NOT NULL DEFAULT '', logo_path VARCHAR(255),
 primary_color CHAR(7) NOT NULL DEFAULT '#004aad', accent_color CHAR(7) NOT NULL DEFAULT '#ffde59',
 show_title BOOLEAN NOT NULL DEFAULT TRUE, is_active BOOLEAN NOT NULL DEFAULT TRUE,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS bio_sections (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, title VARCHAR(150) NOT NULL,
 sort_order INT NOT NULL DEFAULT 0, is_active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS bio_links (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, title VARCHAR(150) NOT NULL,
 subtitle VARCHAR(200) NOT NULL DEFAULT '', url VARCHAR(2048) NOT NULL,
 icon ENUM('website','whatsapp','maps','instagram','catalog','phone') NOT NULL DEFAULT 'website',
 sort_order INT NOT NULL DEFAULT 0, is_active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 section_id BIGINT UNSIGNED NULL,
 CONSTRAINT bio_links_section_fk FOREIGN KEY (section_id) REFERENCES bio_sections(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
