CREATE TABLE IF NOT EXISTS bio_settings (
 id INT UNSIGNED PRIMARY KEY, title VARCHAR(150) NOT NULL,
 description VARCHAR(500) NOT NULL DEFAULT '', logo_path VARCHAR(255),
 primary_color CHAR(7) NOT NULL DEFAULT '#004aad', accent_color CHAR(7) NOT NULL DEFAULT '#ffde59',
 show_title BOOLEAN NOT NULL DEFAULT TRUE, is_active BOOLEAN NOT NULL DEFAULT TRUE,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
