CREATE TABLE IF NOT EXISTS bio_links (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, title VARCHAR(150) NOT NULL,
 subtitle VARCHAR(200) NOT NULL DEFAULT '', url VARCHAR(2048) NOT NULL,
 icon ENUM('website','whatsapp','maps','instagram','catalog','phone') NOT NULL DEFAULT 'website',
 sort_order INT NOT NULL DEFAULT 0, is_active BOOLEAN NOT NULL DEFAULT TRUE,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
